# Generated by Django 4.0.5 on 2023-10-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
